# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: auth-service  
  namespace: default
spec:
  selector:
    app: auth-service
  type: NodePort
  ports:
  - name: auth-service
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30005
---

