# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: default
spec:
  selector:
    app: todo-service
  type: NodePort
  ports:
  - name: todo-service
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30004
---

